# timestamp                       : Epoch time [ms]
# avg_motor_current               : Average value of currnet in motor [amp]
# rpm                             : Current rpm of vehicle [rpm]
# temp_fet                        : Current temperature of MOSFET in VESC controller [deg cel]
# temp_motor                      : Current temperature of motor [deg cel]
# v_in                            : Input voltage to motor [v]



int64 timestamp
# float64 amp_hours
# float64 amp_hours_charged
# float64 avg_id
# float64 avg_input_current
# float64 avg_iq
float64 avg_motor_current
# float64 duty_cycle_now
# float64 pid_pos_now
float64 rpm
# float64 tachometer
# float64 tachometer_abs
float64 temp_fet
float64 temp_motor
# float64 time_ms
float64 v_in
# float64 watt_hours
# float64 watt_hours_charged
# bool    jet_data_valid
