# 16384="   GPS Connection Error \n"
# 8192="    Mission Timeout Error \n"
# 4096="    PC connection Error \n"
# 2048="    BME_Back_Error = 2048
# 1024="    Distance < 30[m] \n"
# 512="     Mission Done \n"
# 256="     Modem Stop Error \n"
# 128="     INS Critical Sensor Error \n"
# 64="      BME_Front_Error 
# 32="      Bat Voltage Error \n"
# 16="      INS Connection Error \n"
# 8="       Jet_Motor_Error
# 4="       Servo_Error
# 2="       Altitude Error \n"
# 1="       Depth Error\n"
# 0="       No Error \n"

int64 timestamp
int64 status_code
